### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by 9SL9** [tkmn0/SimpleWebRTCExample_iOS#24]
Hi - thank you so much for sharing your hard work. This has helped me so much.

Do you know I could add in a simple password option so both people need to know a simple password before they are able to join?

Thanks

**Comment by tkmn0** [comment]
Hi, thank you for your comment :) 

1. set up password input view. 
2. modify [signaling message](https://github.com/tkmn0/SimpleWebRTCExample_iOS/blob/master/SimpleWebRTC/Data/SignalingMessage.swift#L21) to be included a password field and value.         
3. validate password when received signaling message([here](https://github.com/tkmn0/SimpleWebRTCExample_iOS/blob/master/SimpleWebRTC/ViewController/ViewController.swift#L278)).

I think this is the easiest way because only need to change client side.
If we need advanced options, I think we should change server side code.

Thanks too.

**Comment by 9SL9** [comment]
Thank you. Yes I was hoping to do it server side also. I guess this would mean looking for the value in the JSON.
